/** Auth */
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'

export const LOGIN_REQEST = 'LOGIN_REQEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT_REQEST = 'LOGOUT_REQEST'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const CALL_REQUEST = 'CALL_REQUEST'
export const CALL_SUCCESS = 'CALL_SUCCESS'
export const CALL_FAILURE = 'CALL_FAILURE'
export const CALL_RECEIVE = 'CALL_RECEIVE'
export const CALL_REJECT = 'CALL_REJECT'
export const CALL_ACCEPT = 'CALL_ACCEPT'
export const CALL_STOP_REQUEST = 'CALL_STOP_REQUEST'
export const CALL_STOP_SUCCESS = 'CALL_STOP_SUCCESS'
export const CALL_STOP_FAILURE = 'CALL_STOP_FAILURE'

export const SESSION_RESERVED = 'SESSION_RESERVED'
export const SHARE_FAILURE = 'SHARE_FAILURE'

export const SCREEN_REQUEST = 'SCREEN_REQUEST'
export const SCREEN_RECEIVE = 'SCREEN_RECEIVE'
export const SCREEN_SUCCESS = 'SCREEN_SUCCESS'
export const SCREEN_FAILURE = 'SCREEN_FAILURE'

export const SCREEN_STOP_REQUEST = 'SCREEN_STOP_REQUEST'
export const SCREEN_STOP_SUCCESS = 'SCREEN_STOP_SUCCESS'
export const SCREEN_STOP_FAILURE = 'SCREEN_STOP_FAILURE'

/** File share actions */
export const FILE_SHARE_REQUEST = 'FILE_SHARE_REQUEST'
export const FILE_SHARE_SUCCESS = 'FILE_SHARE_SUCCESS'
export const FILE_SHARE_FAILURE = 'FILE_SHARE_FAILURE'
export const FILE_SHARE_RECEIVE = 'FILE_SHARE_RECEIVE'

export const FILE_UPLOAD_SUCCESS = 'FILE_UPLOAD_SUCCESS'
export const FILE_UPLOAD_FAILURE = 'FILE_UPLOAD_FAILURE'

export const FILE_CHANGE_REQUEST = 'FILE_CHANGE_REQUEST'
export const FILE_CHANGE_SUCCESS = 'FILE_CHANGE_SUCCESS'
export const FILE_CHANGE_FAILURE = 'FILE_CHANGE_FAILURE'
export const FILE_CHANGE_RECEIVE = 'FILE_CHANGE_RECEIVE'

/** whiteboard actions */
export const DRAWING = 'DRAWING'
export const ERASERING = 'ERASERING'
export const RESET = 'RESET'
export const CHANGE_PEN_COLOR = 'CHANGE_PEN_COLOR'
export const CHANGE_TOOL_TYPE = 'CHANGE_TOOL_TYPE'
export const CHANGE_PEN_THICKNESS = 'CHANGE_PEN_THICKNESS'
export const CHANGE_ERASER_SIZE = 'CHANGE_ERASER_SIZE'
